# Screenshots

control + shift + s
    screenshotter -a
control + shift + alt + s
    @enter screenshot && echo "screenshot" > ~/.config/waybar/swhkd‐mode

mode screenshot
q
    @escape && echo "normal" > ~/.config/waybar/swhkd‐mode
f
    # Full screenshot
    screenshotter -f && @escape && echo "normal" > ~/.config/waybar/swhkd-mode
a
    # Selected Area
    screenshotter -a
s
    # selected window
    screenshotter -s
w
    # focused window
    screenshotter -w
endmode
