# Menus
super + d
    rofi -show combi -combi-modi "drun,calc" -modi combi -combi-hide-mode-prefix
super + g
    rofi -modi games -show games -theme games-default
super + m
    rofi -modi "power-menu:rofi-power-menu" -show power-menu
