# Media Keys
XF86AudioRaiseVolume
    volumectl -u up
XF86AudioLowerVolume
    volumectl -u down
XF86AudioMute
    volumectl toggle-mute
XF86AudioMicMute
    volumectl -m toggle-mute

# Media player controls
XF86AudioPlay
    playerctl play-pause
XF86AudioNext
    playerctl next
XF86AudioPrev
    playerctl previous
