# Window Movement
super + shift + {h,l,j,k}
    swaymsg move {left,right,up,down}
super + {h,l,j,k}
    swaymsg focus {left,right,up,down}
super + shift + q
    swaymsg kill

# Workspaces
super + {1,2,3,4,5,6,7,8,9,0}
    swaymsg workspace number {1,2,3,4,5,6,7,8,9,0}
super + shift + {s,g}
    swaymsg workspace {"special","games"}
super + shift + {1,2,3,4,5,6,7,8,9,0}
    swaymsg move container to workspace number {1,2,3,4,5,6,7,8,9,0}
super + control + {h,l}
    swaymsg workspace {next_on_output,prev_on_output}

# Layout stuff
super + {b,v}
    swaymsg {splith,splitv}
super + {s,w,e}
    swaymsg layout {stacking,tabbed,toggle split}
super + f
    swaymsg fullscreen
super + shift + space
    swaymsg floating toggle
super + space
    swaymsg focus mode_toggle
super + a
    swaymsg focus parent

# Scratchpad
super + shift + minus
    swaymsg move scratchpad
super + minus
    swaymsg scratchpad show

# Resize mode
super + r
    @enter resize && echo "resize" > ~/.config/waybar/swhkd‐mode

mode resize
q
    @escape && echo "normal" > ~/.config/waybar/swhkd‐mode
{h,j,k,l}
    swaymsg resize {shrink width 10px,grow height 10px,shrink height 10px,grow width 10px}
endmode # use endmode if you want to set more key bindings for normal mode

# Misc
super + shift + c
    swaymsg reload
