exec gammastep -P -O 3600
exec waybar
#exec ~/.config/sway/scripts/start-swhkd.sh
exec ~/.config/sway/scripts/move-games-to-workspace.sh
exec_always kanata-starter

exec wezterm start -- /bin/sh -c ~/.config/sway/scripts/start_btop.sh

exec ~/.config/sway/scripts/swayidle.sh
exec mako
